<?xml version="1.0" encoding="UTF-8"?>

 <!DOCTYPE biblioteca [

 <!-- DEFINIMOS ELEMENTOS -->

        <!ELEMENT biblioteca (libros, revistas,periodicos)>

        
        <!ELEMENT libros (libro*)>

        <!ELEMENT libro (titulo_libro, indice_libro, sinopsis,capitulos)>

        <!ELEMENT titulo_libro (#PCDATA)>
        <!ELEMENT indice_libro (#PCDATA)>
        <!ELEMENT sinopsis (#PCDATA)>
 
        <!ELEMENT capitulos (capitulo*)>
        
        <!ELEMENT capitulo (titulo_capitulo, contenido_capitulo)>
        <!ELEMENT titulo_capitulo (#PCDATA)>
        <!ELEMENT contenido_capitulo (#PCDATA)>


        <!ELEMENT revistas (revista*)>
        <!ELEMENT revista (titulo, numero_revista,indice_revista,secciones_revista)>
        
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT numero_revista (#PCDATA)>
        <!ELEMENT indice_revista (#PCDATA)>
        <!ELEMENT secciones_revista (seccion_revista*)>
        
        <!ELEMENT seccion_revista (contenido_seccion_revista)>
        <!ELEMENT contenido_seccion_revista (#PCDATA)>


        <!ELEMENT periodicos (periodico*)>

        <!ELEMENT periodico (indice_periodico, secciones_periodico)>
        <!ELEMENT indice_periodico (#PCDATA)>
        <!ELEMENT secciones_periodico (seccion_periodico*)>

        <!ELEMENT seccion_periodico (articulos)>
        <!ELEMENT articulos (articulo*)>

        <!ELEMENT articulo (contenido_articulo)>
        <!ELEMENT contenido_articulo (#PCDATA)>

 
 <!-- DEFINIMOS LOS ATRIBUTOS -->

 <!ATTLIST libro id ID #REQUIRED>
 <!ATTLIST libro tipo_clase (novela | infantil | didactico) #REQUIRED>
 <!ATTLIST libro numero_paginas CDATA #REQUIRED>
 <!ATTLIST capitulo numero_paginas CDATA #REQUIRED>
 <!ATTLIST contenido_capitulo enlace_informacion CDATA #REQUIRED>

 <!ATTLIST revista id ID #REQUIRED>
 <!ATTLIST revista tipo_clase (informatica | corazon | coches | investigacion | otras ) #REQUIRED>
 <!ATTLIST revista numero_paginas CDATA #REQUIRED>
 <!ATTLIST seccion_revista numero_paginas CDATA #REQUIRED>
 <!ATTLIST contenido_seccion_revista enlace_informacion CDATA #REQUIRED>

 <!ATTLIST periodico id ID #REQUIRED>
 <!ATTLIST periodico tipo_clase (nacional | internacional) #REQUIRED>
 <!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>
 <!ATTLIST seccion_periodico tiposeccion (economica | opinion | deportes | nacional | internacional) #REQUIRED>
 <!ATTLIST articulo autor CDATA #REQUIRED>
 <!ATTLIST contenido_articulo enlace_informacion CDATA #REQUIRED> 


]>

<biblioteca>


    <libros>


        <libro id="L0001" tipo_clase="novela" numero_paginas="600">

            <titulo_libro></titulo_libro>
            <indice_libro></indice_libro>
            <sinopsis></sinopsis>
            <capitulos>

                <capitulo numero_paginas="300">

                    <titulo_capitulo>cdscsd</titulo_capitulo>
                    <contenido_capitulo enlace_informacion="https:" />

                </capitulo>

                <capitulo numero_paginas="200">

                    <titulo_capitulo>cdscsd</titulo_capitulo>
                    <contenido_capitulo enlace_informacion="https:" />
                </capitulo>

                <capitulo numero_paginas="100">

                    <titulo_capitulo>cdscsd</titulo_capitulo>
                    <contenido_capitulo enlace_informacion="https:" />

                </capitulo>

            </capitulos>

        </libro>

        <libro id="L0002" tipo_clase="infantil" numero_paginas="120">

            <titulo_libro></titulo_libro>
            <indice_libro></indice_libro>
            <sinopsis></sinopsis>
            <capitulos>

                <capitulo numero_paginas="40">

                    <titulo_capitulo>cdscsd</titulo_capitulo>
                    <contenido_capitulo enlace_informacion="https:" />
                </capitulo>

                <capitulo numero_paginas="40">

                    <titulo_capitulo>cdscsd</titulo_capitulo>
                   <contenido_capitulo enlace_informacion="https:" />
                </capitulo>

                <capitulo numero_paginas="40">

                   <titulo_capitulo>cdscsd</titulo_capitulo>
                    <contenido_capitulo enlace_informacion="https:" />

                </capitulo>

            </capitulos>

        </libro>

        <libro id="L0003" tipo_clase="didactico" numero_paginas="200">

            <titulo_libro></titulo_libro>
            <indice_libro></indice_libro>
            <sinopsis></sinopsis>
            <capitulos>

                <capitulo numero_paginas="100">

                    <titulo_capitulo>cdscsd</titulo_capitulo>
                    <contenido_capitulo enlace_informacion="https:" />

                </capitulo>

                <capitulo numero_paginas="60">

                    <titulo_capitulo>cdscsd</titulo_capitulo>
                    <contenido_capitulo enlace_informacion="https:" />
                </capitulo>

                <capitulo numero_paginas="40">

                    <titulo_capitulo>cdscsd</titulo_capitulo>
                    <contenido_capitulo enlace_informacion="https:" />
                </capitulo>

            </capitulos>

        </libro>


    </libros>

    <revistas>

        <revista id="R0001" tipo_clase="informatica" numero_paginas="300">

            <titulo></titulo>
            <numero_revista></numero_revista>
            <indice_revista></indice_revista>

            <secciones_revista>

                <seccion_revista numero_paginas="100">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

                <seccion_revista numero_paginas="100">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

                <seccion_revista numero_paginas="100">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

            </secciones_revista>


        </revista>

        <revista id="R0002" tipo_clase= "corazon" numero_paginas="180">

            <titulo></titulo>
            <numero_revista></numero_revista>
            <indice_revista></indice_revista>

            <secciones_revista>

                <seccion_revista numero_paginas="60">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

                <seccion_revista numero_paginas="60">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

                <seccion_revista numero_paginas="60">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

            </secciones_revista>


        </revista>

        <revista id="R0003" tipo_clase="coches" numero_paginas="200">

            <titulo></titulo>
            <numero_revista></numero_revista>
            <indice_revista></indice_revista>

            <secciones_revista>

                <seccion_revista numero_paginas="100">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

                <seccion_revista numero_paginas="50">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

                <seccion_revista numero_paginas="50">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

            </secciones_revista>


        </revista>

        <revista id="R0004" tipo_clase="investigacion" numero_paginas="500">

            <titulo></titulo>
            <numero_revista></numero_revista>
            <indice_revista></indice_revista>

            <secciones_revista>

                <seccion_revista numero_paginas="300">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

                <seccion_revista numero_paginas="100">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

                <seccion_revista numero_paginas="100">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

            </secciones_revista>


        </revista>

        <revista id="R0005" tipo_clase="otras" numero_paginas="400">

            <titulo></titulo>
            <numero_revista></numero_revista>
            <indice_revista></indice_revista>

            <secciones_revista>

                <seccion_revista numero_paginas="200">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

                <seccion_revista numero_paginas="100">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

                <seccion_revista numero_paginas="100">

                    <contenido_seccion_revista enlace_informacion="https:" />

                </seccion_revista>

            </secciones_revista>


        </revista>

    </revistas>

    <periodicos>

        <periodico id="P0001" tipo_clase="nacional" fecha_publicacion="10/07/2022">

            <indice_periodico></indice_periodico>

            <secciones_periodico>

                <seccion_periodico tiposeccion="economica">

                    <articulos>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                    </articulos>

                </seccion_periodico>

                <seccion_periodico tiposeccion="opinion">

                    <articulos>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                    </articulos>

                </seccion_periodico>

            </secciones_periodico>


        </periodico>

        <periodico id="P0002" tipo_clase="internacional" fecha_publicacion="11/07/2022">

            <indice_periodico></indice_periodico>

            <secciones_periodico>

                <seccion_periodico tiposeccion="deportes">

                    <articulos>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                    </articulos>

                </seccion_periodico>

                <seccion_periodico tiposeccion="nacional">

                    <articulos>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                    </articulos>

                </seccion_periodico>

                <seccion_periodico tiposeccion="internacional">

                    <articulos>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                        <articulo autor="JuanBrotons">

                            <contenido_articulo enlace_informacion="https:" />

                        </articulo>

                    </articulos>

                </seccion_periodico>

            </secciones_periodico>


        </periodico>

    </periodicos>


</biblioteca>