=== fanybt/AE-2-XML-DTD-XSD/DTD_biblioteca_v.dtd
<!ELEMENT biblioteca (libros, revistas, periodicos)>

<!-- LIBROS -->
<!ELEMENT libros (libro+)>

<!ELEMENT libro (titulo, capitulos, indice, sinopsis)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulos (capitulo+)>
<!ELEMENT indice (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>

<!ELEMENT capitulo (titulo_cap, contenido)>
<!ELEMENT titulo_cap (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>

<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro tipo_clase (novela | infantil | didactico) #REQUIRED>
<!ATTLIST libro paginas CDATA #REQUIRED>
<!ATTLIST capitulo paginas_capitulo CDATA #REQUIRED>
<!ATTLIST contenido informacion CDATA #IMPLIED>

<!-- REVISTAS -->
<!ELEMENT revistas (revista+)>

<!ELEMENT revista (titulo_rev, numero_revista, indice_rev?, secciones)>
<!ELEMENT titulo_rev (#PCDATA)>
<!ELEMENT numero_revista (#PCDATA)>
<!ELEMENT indice_rev (#PCDATA)>
<!ELEMENT secciones (seccion+)>

<!ELEMENT seccion (contenido_rev)>
<!ELEMENT contenido_rev (#PCDATA)>

<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista tipo_clase (informatica | corazon | coches | investigacion | otras) #REQUIRED>
<!ATTLIST revista paginas CDATA #REQUIRED>
<!ATTLIST seccion paginas CDATA #REQUIRED>
<!ATTLIST contenido_rev informacion CDATA #IMPLIED>

<!-- PERIODICOS -->
<!ELEMENT periodicos (periodico+)>

<!ELEMENT periodico (secciones_per, indice_per)>
<!ELEMENT secciones_per (seccion_per+)>
<!ELEMENT indice_per (#PCDATA)>

<!ELEMENT seccion_per (articulos)>
<!ELEMENT articulos (articulo+)>
<!ELEMENT articulo (contenido_per)>
<!ELEMENT contenido_per (#PCDATA)>

<!ATTLIST periodico id ID #REQUIRED>
<!ATTLIST periodico tipo_clase (nacional | internacional) #REQUIRED>
<!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>
<!ATTLIST seccion_per tipo_seccion (economica | opinion | deportes | nacional | internacional) #REQUIRED>
<!ATTLIST articulo autor CDATA #REQUIRED>
<!ATTLIST contenido_per informacion CDATA #IMPLIED>

=== fanybt/AE-2-XML-DTD-XSD/DTD_biblioteca_v.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "DTD_biblioteca_v.dtd">
<biblioteca>
    <libros>
        <libro id="L0001" tipo_clase="infantil" paginas="38"><!-- novela, infantil o didáctico -->
            <titulo>Siete días, 7 cuentos</titulo>
            <capitulos>
                <capitulo paginas_capitulo="4">
                    <titulo_cap>Mi tío escultor</titulo_cap>
                    <contenido informacion="https://www.margenlibros.com/libro/siete-dias-7-cuentos_120854"></contenido>
                </capitulo>
                <capitulo paginas_capitulo="4">
                    <titulo_cap>Un corte de pelo</titulo_cap>
                    <contenido informacion="https://www.margenlibros.com/libro/siete-dias-7-cuentos_120854"></contenido>
                </capitulo>
                <capitulo paginas_capitulo="4">
                    <titulo_cap>Una calamidad de robot</titulo_cap>
                    <contenido informacion="https://www.margenlibros.com/libro/siete-dias-7-cuentos_120854"></contenido>
                </capitulo>
                <capitulo paginas_capitulo="4">
                    <titulo_cap>El hombre más serio del mundo</titulo_cap>
                    <contenido informacion="https://www.margenlibros.com/libro/siete-dias-7-cuentos_120854"></contenido>
                </capitulo>
                <capitulo paginas_capitulo="4">
                    <titulo_cap>Ranas, príncipes y princesas</titulo_cap>
                    <contenido informacion="https://www.margenlibros.com/libro/siete-dias-7-cuentos_120854"></contenido>
                </capitulo>
                <capitulo paginas_capitulo="4">
                    <titulo_cap>Una redacción salvaje</titulo_cap>
                    <contenido informacion="https://www.margenlibros.com/libro/siete-dias-7-cuentos_120854"></contenido>
                </capitulo>
                <capitulo paginas_capitulo="3">
                    <titulo_cap>Una memoria prodigiosa</titulo_cap>
                    <contenido informacion="https://www.margenlibros.com/libro/siete-dias-7-cuentos_120854"></contenido>
                </capitulo>
            </capitulos>
            <indice>Mi tío escultor, 4. Un corte de pelo, 8. Una calamidad de robot, 12. El hombre más serio del mundo, 16.
            Ranas, príncipes y princesas, 20. Una redacción salvaje, 24. Una memoria prodigiosa, 28</indice>
            <sinopsis>Uno para cada día! 7 fantásticos cuentos de Daniel Nesquens ilustrados por importantes Premios
            Nacionales de Ilustración.</sinopsis>
        </libro>
        <libro id="L0002" tipo_clase="infantil" paginas="172">
            <titulo>Sólo tú puedes salvar a la humanidad</titulo>
            <capitulos>
                <capitulo paginas_capitulo="10">
                    <titulo_cap>El héroe con mil vidas extra</titulo_cap>
                    <contenido informacion="https://www.casadellibro.com/libro-solo-tu-puedes-salvar-a-la-humanidad/9788420448404/9016"></contenido>
                </capitulo>
                <capitulo paginas_capitulo="10">
                    <titulo_cap>Para jugar, accionar los mandos</titulo_cap>
                    <contenido informacion="https://www.casadellibro.com/libro-solo-tu-puedes-salvar-a-la-humanidad/9788420448404/9016"></contenido>
                </capitulo>
                <capitulo paginas_capitulo="15">
                    <titulo_cap>Cereales asesinos</titulo_cap>
                    <contenido informacion="https://www.casadellibro.com/libro-solo-tu-puedes-salvar-a-la-humanidad/9788420448404/9016"></contenido>
                </capitulo>
                <capitulo paginas_capitulo="14">
                    <titulo_cap>Nadie muere de verdad</titulo_cap>
                    <contenido informacion="https://www.casadellibro.com/libro-solo-tu-puedes-salvar-a-la-humanidad/9788420448404/9016"></contenido>
                </capitulo>
                <capitulo paginas_capitulo="12">
                    <titulo_cap>Si no lo haces tú, ¿quién lo hará?</titulo_cap>
                    <contenido informacion="https://www.casadellibro.com/libro-solo-tu-puedes-salvar-a-la-humanidad/9788420448404/9016"></contenido>
                </capitulo>
                <capitulo paginas_capitulo="17">
                    <titulo_cap>Porciones de pollo en el espacio</titulo_cap>
                    <contenido informacion="https://www.casadellibro.com/libro-solo-tu-puedes-salvar-a-la-humanidad/9788420448404/9016"></contenido>
                </capitulo>
            </capitulos>
            <indice>1 El héroe con mil vidas extra, 9. 2 Para jugar, accionar los mandos, 19. 3 Cereales asesinos, 33.
            4 Nadie muere de verdad, 48. 5 Si no lo haces tú, ¿quién lo hará?, 63. 6 Porciones de pollo en el espacio, 75.</indice>
            <sinopsis>A Johnny, un amigo le ha dejado el nuevo juego de ordenador, Sólo tú puedes salvar a la humanidad.
            Cuando se dispone a salvarla destruyendo las naves de los ScreeWees, aparece en la pantalla un mensaje:
            Nos rendimos. No queremos más guerras Johnny dialoga con la Capitana e, impresionado por las razones que le da,
            decide no atacarles y ayudarles a retirarse a su lugar de origen, donde estarán a salvo. Así se ve envuelto
            en una emocionante aventura espacial que comparte con tres amigos y una chica fuera de lo común. Todo ello
            le hará reflexionar sobre la guerra, la paz, la violencia injustificada, la igualdad entre los sexos,
            la solidaridad... y saldrá renovado de esta insólita aventura.</sinopsis>
        </libro>
        <libro id="L0003" tipo_clase="novela" paginas="128">
            <titulo>La metamorfosis</titulo>
            <capitulos>
                <capitulo paginas_capitulo="90">
                    <titulo_cap>La metamorfosis</titulo_cap>
                    <contenido informacion="https://www.alianzaeditorial.es/primer_capitulo/la-metamorfosis.pdf"></contenido>
                </capitulo>
                <capitulo paginas_capitulo="20">
                    <titulo_cap>Un artista del hambre</titulo_cap>
                    <contenido informacion="https://www.alianzaeditorial.es/libro/bibliotecas-de-autor/la-metamorfosis-franz-kafka-9788420651361/"></contenido>
                </capitulo>
                <capitulo paginas_capitulo="10">
                    <titulo_cap>Un artista del trapecio</titulo_cap>
                    <contenido informacion="https://www.alianzaeditorial.es/libro/bibliotecas-de-autor/la-metamorfosis-franz-kafka-9788420651361/"></contenido>
                </capitulo>
            </capitulos>
            <indice>9 La metamorfosis.
                    99 Un artista del hambre.
                    119 Un artista del trapecio.</indice>
            <sinopsis>«Al despertar Gregorio Samsa una mañana, tras un sueño intranquilo, se encontró
            en su cama convertido en un monstruoso insecto.» Tal es el abrupto comienzo, que nos sitúa
            de raíz bajo unas reglas distintas, de "La metamorfosis", sin duda alguna la obra de Franz Kafka
            que ha alcanzado mayor celebridad. Escrito en 1912 y publicado en 1916, este relato es considerado
            una de las obras maestras del siglo xx por sus innegables rasgos precursores y el caudal de ideas
            e interpretaciones que desde siempre ha suscitado. Completan este volumen los relatos «Un artista
            del hambre» y «Un artista del trapecio».</sinopsis>
        </libro>
    </libros>

    <revistas>
        <revista id="R0001" tipo_clase="investigacion" paginas="298"><!--informática, corazón, coches, investigación y otras -->
            <titulo_rev>Revista de Investigación Educativa</titulo_rev>
            <numero_revista>Vol. 41, Núm. 1</numero_revista>
            <indice_rev>Educating the Youth to Develop Life Purpose: An Eco-systemic Approach, 15-31.
            Evaluación de la competencia digital del alumnado de Educación Primaria, 33-50.
            Análisis de la autopercepción de la competencia digital docente en la formación
            inicial de maestros y maestras, 51-67.
            El programa de enseñanza bilingüe en Andalucía según los auxiliares de conversación, 69-85.
            </indice_rev>
            <secciones>
                <seccion paginas="17">
                    <contenido_rev informacion="https://revistas.um.es/rie/article/view/539521/336291">Educating the Youth
                    to Develop Life Purpose: An Eco-systemic Approach</contenido_rev>
                </seccion>
                <seccion paginas="17">
                    <contenido_rev informacion="https://revistas.um.es/rie/article/view/520091">Evaluación de la
                    competencia digital del alumnado de Educación Primaria</contenido_rev>
                </seccion>
                <seccion paginas="16">
                    <contenido_rev informacion="https://revistas.um.es/rie/article/view/501151">Análisis de la autopercepción
                    de la competencia digital docente en la formación inicial de maestros y maestras</contenido_rev>
                </seccion>
                <seccion paginas="16">
                    <contenido_rev informacion="https://revistas.um.es/rie/article/view/495781">El programa de enseñanza bilingüe
                    en Andalucía según los auxiliares de conversación</contenido_rev>
                </seccion>
            </secciones>
        </revista>
        <revista id="R0002" tipo_clase="informatica" paginas="100">
            <titulo_rev>Revista de tecnología e informática histórica</titulo_rev>
            <numero_revista>Volumen 2, Número 1</numero_revista>
            <indice_rev>1 Descifrando la mecánica del cielo. El mecanismo de Anticitera
            Diego Gustavo Macchi 17 Continuar el camino. Cincuenta años de computación en Argentina
